[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'rm -rf node_modules/.cache || true',
  'npm cache clean --force',
  'npm install --no-optional',
  'npm install @rollup/rollup-linux-x64-gnu --save-optional'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npx serve dist -s -l 10000'
